In [1]:
import pandas as pd

## Analyse Exploiratoire

In [2]:
# Lecture du fichier
data = pd.read_csv("../Agriculture/crop_yield.csv")
data.head()

,Region,Soil_Type,Crop,Rainfall_mm,Temperature_Celsius,Fertilizer_Used,Irrigation_Used,Weather_Condition,Days_to_Harvest,Yield_tons_per_hectare
0,West,Sandy,Cotton,897.077239,27.676966,False,True,Cloudy,122,6.555816
1,South,Clay,Rice,992.673282,18.026142,True,True,Rainy,140,8.527341
2,North,Loam,Barley,147.998025,29.794042,False,False,Sunny,106,1.127443
3,North,Sandy,Soybean,986.866331,16.644190,False,True,Rainy,146,6.517573
4,South,Silt,Wheat,730.379174,31.620687,True,True,Cloudy,110,7.248251

In [3]:
print("format:" , data.shape)
print("-----------------------------")
print("Doublon:" , data.duplicated().sum())
print("-----------------------------")
print("Valeur manquantes:" , data.isnull())
print("-----------------------------")
print("Total valeur manquantes:" , data.isnull().sum().sum())

format: (1000000, 10)
-----------------------------
Doublon: 0
-----------------------------
Valeur manquantes:         Region  Soil_Type   Crop  Rainfall_mm  Temperature_Celsius  \
0        False      False  False        False                False
1        False      False  False        False                False
2        False      False  False        False                False
3        False      False  False        False                False
4        False      False  False        False                False
...        ...        ...    ...          ...                  ...
999995   False      False  False        False                False
999996   False      False  False        False                False
999997   False      False  False        False                False
999998   False      False  False        False                False
999999   False      False  False        False                False

        Fertilizer_Used  Irrigation_Used  Weather_Condition  Days_to_Harvest  \
0                 False            False              False            False
1                 False            False              False            False
2                 False            False              False            False
3                 False            False              False            False
4                 False            False              False            False
...                 ...              ...                ...              ...
999995            False            False              False            False
999996            False            False              False            False
999997            False            False              False            False
999998            False            False              False            False
999999            False            False              False            False

        Yield_tons_per_hectare
0                        False
1                        False
2                        False
3                        False
4                        False
...                        ...
999995                   False
999996                   False
999997                   False
999998                   False
999999                   False

[1000000 rows x 10 columns]
-----------------------------
Total valeur manquantes: 0

* D'après cette prémière information nous constatons que le jeu de donnée ne contient pas de doublon et ne contient pas de valeur manquantes

In [4]:
# Inspectons les colonnes
data.columns

Index(['Region', 'Soil_Type', 'Crop', 'Rainfall_mm', 'Temperature_Celsius',
       'Fertilizer_Used', 'Irrigation_Used', 'Weather_Condition',
       'Days_to_Harvest', 'Yield_tons_per_hectare'],
      dtype='object')

In [5]:
data['Region'].unique()

array(['West', 'South', 'North', 'East'], dtype=object)

In [6]:
data['Soil_Type'].unique()

array(['Sandy', 'Clay', 'Loam', 'Silt', 'Peaty', 'Chalky'], dtype=object)

In [8]:
(data["Yield_tons_per_hectare"] < 0).sum()

np.int64(231)

In [9]:
nb_negatifs = (data["Yield_tons_per_hectare"] < 0).sum()

pourcentage = (
    nb_negatifs / len(data)
) * 100

print(f"Nombre de valeurs négatives : {nb_negatifs}")
print(f"Pourcentage : {pourcentage:.4f}%")

Nombre de valeurs négatives : 231
Pourcentage : 0.0231%

In [10]:
data['Yield_tons_per_hectare'].describe()

count    1000000.000000
mean           4.649472
std            1.696572
min           -1.147613
25%            3.417637
50%            4.651808
75%            5.879200
max            9.963372
Name: Yield_tons_per_hectare, dtype: float64

In [14]:
data[data["Yield_tons_per_hectare"] < 0].head(10)

,Region,Soil_Type,Crop,Rainfall_mm,Temperature_Celsius,Fertilizer_Used,Irrigation_Used,Weather_Condition,Days_to_Harvest,Yield_tons_per_hectare
756,East,Peaty,Cotton,101.019421,33.804131,False,False,Rainy,117,-0.007103
7799,South,Chalky,Rice,108.804894,18.004082,False,False,Sunny,86,-0.061283
8421,East,Chalky,Soybean,168.120735,38.473430,False,False,Cloudy,111,-0.119911
9553,North,Silt,Wheat,156.607973,16.610257,False,False,Sunny,129,-0.193093
15435,South,Chalky,Maize,177.481344,27.719742,False,False,Sunny,94,-0.009811
19517,North,Clay,Maize,107.845638,21.855075,False,False,Rainy,118,-0.265207
22552,East,Sandy,Barley,136.608277,16.723985,False,False,Sunny,101,-0.235296
25967,West,Sandy,Wheat,143.407729,16.252040,False,False,Rainy,77,-0.023612
33285,West,Sandy,Rice,103.921766,16.314536,False,False,Cloudy,80,-0.060267
34902,East,Chalky,Soybean,144.431171,37.817570,False,False,Sunny,112,-0.028898

* Conclusion : 
    * Le dataset crop_yield.csv a été écarté de l'étude pour deux raisons principales. Premièrement, il contient des rendements agricoles négatifs (Yield_tons_per_hectare < 0), ce qui n'est pas physiquement plausible pour une production agricole. Deuxièmement, la variable géographique est représentée par des régions génériques (North, South, East, West) plutôt que par des pays réels, ce qui est incompatible avec l'objectif du projet basé sur des données par pays (Area) et par année. Enfin, sa structure ne contient pas certaines variables essentielles utilisées dans le modèle final, notamment l'année et l'utilisation de pesticides. Le dataset a donc été jugé non pertinent pour répondre aux objectifs de prédiction et de recommandation agricole du projet.